---

- name: PostgreSQL BDR | Backup postgresql.conf
  command: dpkg-divert --quiet --local --divert {{ pgbdr_conf_directory }}/postgresql.conf.dpkg-divert --rename {{ pgbdr_conf_directory }}/postgresql.conf
  args:
    creates: "{{ pgbdr_conf_directory }}/postgresql.conf.dpkg-divert"

- name: PostgreSQL BDR | Update postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ pgbdr_conf_directory }}/postgresql.conf"
    owner: "{{ pgbdr_service_user }}"
    group: "{{ pgbdr_service_group }}"
    mode: 0644
  notify: PostgreSQL BDR | Restart

- name: PostgreSQL BDR | Create include directory
  file:
    path: "{{ pgbdr_conf_directory }}/conf.d"
    state: directory
    owner: "{{ pgbdr_service_user }}"
    group: "{{ pgbdr_service_group }}"
    mode: 0755

- name: PostgreSQL BDR | Include configuration
  template:
    src: bdr.conf.j2
    dest: "{{ pgbdr_conf_directory }}/conf.d/bdr.conf"
    owner: "{{ pgbdr_service_user }}"
    group: "{{ pgbdr_service_group }}"
    mode: 0644
  notify: PostgreSQL BDR | Restart

- meta: flush_handlers
