---

- name: PostgreSQL BDR | Install monit script
  template:
    src: pgbdrmonit.py.j2
    dest: /usr/local/bin/pgbdrmonit.py
    mode: 0755
  when: pgbdr_monitoring

- name: PostgreSQL BDR | Install monit cron
  template:
    src: pgbdrmonit.cron.j2
    dest: /etc/cron.d/pgbdrmonit
    mode: 0644
  when: pgbdr_monitoring
